name: Tagged Release
on:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write
jobs:
  release-mac:
    runs-on: macos-latest
    steps:
      - name: ⬇️ Checkout sources
        uses: actions/checkout@v3
      - name: 🏗️ Setup project files
        run: |
          git submodule update --init
          mkdir build
          cd build
          cmake -GXcode ..
      - name: 🛠️ Build Hyde
        run: |
          cd build
          xcodebuild -quiet -target hyde -configuration Release
      - name: 🗜️ Create archive
        run: |
          cd build/Release
          # xattr -d com.apple.quarantine hyde
          tar -zcvf hyde-${{github.ref_name}}-macos-${{runner.arch}}.tgz hyde
      - name: ✍️ Post archive
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files:
            build/Release/hyde-${{github.ref_name}}-macos-${{runner.arch}}.tgz
  release-linux:
    runs-on: ubuntu-20.04
    steps:
      - name: ⬇️ Checkout sources
        uses: actions/checkout@v3
      - name: 🏗️ Setup project files
        run: |
          sudo apt-get install libllvm13 llvm-13 llvm-13-dev
          sudo apt-get install clang-tools-13 libclang-common-13-dev clang-13 libclang-13-dev
          sudo apt-get install ninja-build
          git submodule update --init
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -GNinja ..
      - name: 🛠️ Build Hyde
        run: |
          cd build
          ninja
      - name: 🗜️ Create archive
        run: |
          cd build
          tar -zcvf hyde-${{github.ref_name}}-linux-${{runner.arch}}.tgz hyde
      - name: ✍️ Post archive
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files:
            build/hyde-${{github.ref_name}}-linux-${{runner.arch}}.tgz
